### ISSUE TITLE
(non-issue)could this chat bot used in chinese language?

### ISSUE THREAD

**Issue by albertyou2** [llSourcell/tensorflow_chatbot#16]
@llSourcell hi
great work!

I 'm wondering if this project could be used for chinese language?
If ,it is could .how to do this work?
I just need a chinese conversation  file which contains ASK and Answer in separate line .Right?  

could you please give a instructions for doing this ?
Thank you very much !

**Comment by HazeHub** [comment]
This shouldn't be a problem, however you'll have to recreate the vocabularies files along with custom train/test.enc/dec. For this last part you should study suriyadeepan's repo (in the readme)

**Comment by albertyou2** [comment]
Thank you  for your instructions !
 I ' ll try it !
