### ISSUE TITLE
Breaks in latest TensorFlow 1.0.0

### ISSUE THREAD

**Issue by Graystripe17** [llSourcell/tensorflow_chatbot#24]
I spent a few hours trying to translate this into TF 1.0.0 based on the error messages. I gave up in a puddle of tears.

I'm going to try this in TF.12.

**Comment by Lezzio** [comment]
Hey!

I'm encountering the same problem on TensorFlow 1.0.0, how did you fix that ? Were you forced to go back to an older version ?

Thanks,

**Comment by Graystripe17** [comment]
@Lezzio Yeah it works on TF 0.12. Check out https://github.com/llSourcell/tensorflow_chatbot/issues/26
I also recommend setting up virtualenv to make clean install directories.

**Comment by Lezzio** [comment]
Thanks I've tried with TensorFlow 0.12.1 but I have the _UNK vocabulary issue. Is it needed to use 0.12.0 or does it come from another source ? (I think that my training sets are well prepared)

**Comment by Graystripe17** [comment]
You made me realize I was using 0.12.1 and I have the _UNKs :(
I don't really know, I'm only on step 4200ish since I'm only running on CPU, not GPU.
I might ask somebody else who's done all the training which version

**Comment by ApleSia** [comment]
How to install TF 0.12.1??

**Comment by leemgs** [comment]
@ApleSia , Specify the version name as follow after unistalling the existing up-to-date TF version.
```bash
ubuntu16.04@leemgs$ sudo pip uninstall tensorflow
ubuntu16.04@leemgs$sudo pip install tensorflow==0.12
```
