### ISSUE TITLE
ImportError: No module named 'tensorflow.models'

### ISSUE THREAD

**Issue by Kronos019** [llSourcell/tensorflow_chatbot#27]
Windows 10
Python=3.5.2
all packages up to date

I have tried it from python shell and cmd with same result:
`Traceback (most recent call last):
  File "C:\Users\aweso\Desktop\tensorflow_chatbot\execute.py", line 31, in <module>
    import seq2seq_model
  File "C:\Users\aweso\Desktop\tensorflow_chatbot\seq2seq_model.py", line 28, in <module>
    from tensorflow.models.rnn.translate import data_utils
ImportError: No module named 'tensorflow.models'`

**Comment by Graystripe17** [comment]
You need python 2.7. I recommend setting up a virtualenv.

Also make sure you're running TensorFlow 0.12.0, not the recent TensorFlow 1.0.0. Once, again, virtualenv is helpful

**Comment by Kronos019** [comment]
I downgraded tensorflow to 0.12 and used [https://github.com/llSourcell/tensorflow_chatbot/issues/22](url) to have it work with python 3
The problem is fixed
