### ISSUE TITLE
ValueError: Attempt to reuse RNNCell

### ISSUE THREAD

**Issue by Denisolt** [llSourcell/tensorflow_chatbot#34]
After editing the seq2seq_model.py file. I changed cells values from tf.rnn to tf.contrib.rnn and etc. 
Now I am getting this error:

ValueError: Attempt to reuse RNNCell <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.GRUCell object at 0x11b9f5790> with a different variable scope than its first use.  First use of cell was with scope 'embedding_attention_seq2seq/rnn/multi_rnn_cell/cell_0/gru_cell', this attempt is with scope 'embedding_attention_seq2seq/rnn/multi_rnn_cell/cell_1/gru_cell'.  Please create a new instance of the cell if you would like it to use a different set of weights.  If before you were using: MultiRNNCell([GRUCell(...)] * num_layers), change to: MultiRNNCell([GRUCell(...) for _ in range(num_layers)]).  If before you were using the same cell instance as both the forward and reverse cell of a bidirectional RNN, simply create two instances (one for forward, one for reverse).  In May 2017, we will start transitioning this cell's behavior to use existing stored weights, if any, when it is called with scope=None (which can lead to silent model degradation, so this error will remain until then.)

Any idea? 
thank you in advance

**Comment by Arka161** [comment]
I've the same error. 
It doesn't fix ever after using their documented code

**Comment by jonsanti** [comment]
I have the same error as well. Any info on fixes?

**Comment by Denisolt** [comment]
@Arka161 @jonsanti 
Found a simple solution:
- Set up a virtual environment
```bash
virtualenv local
cd local/bin/activate
```
- Install Tensorflow 0.12
```bash
pip install tensorflow==0.12
```
